### ISSUE TITLE
The site to submit is broken

### ISSUE THREAD

**Issue by Joostvanderlaan** [chromium/hstspreload.appspot.com#44]
When submitting a site, loader keeps spinning for minutes and minutes. SSL checking can be slow, I know (Qualys SSL Labs), but this ends up doing nothing.

**Comment by lgarron** [comment]
I just tested the submission process end-to-end, and it's working fine.

What site are you having trouble with? Also, are you having trouble with the *submission* or for the first step (checking status and eligibility)?

**Comment by dylmye** [comment]
Make sure to enter example.com or www.example.com, not https://example.com or http://example.com.

**Comment by lgarron** [comment]
> Make sure to enter example.com or www.example.com, not https://example.com or http://example.com.

Thanks for this comment. I added code to automatically strip the scheme (in case anyone entered it, despite the example), but there is a bug. I'll file a bug to make sure I fix it.

**Comment by Joostvanderlaan** [comment]
Great, that did the trick. One more note: the submit button does not give any feedback. Would be nice to see a message that your submission is done.

**Comment by lgarron** [comment]
> One more note: the submit button does not give any feedback. Would be nice to see a message that your submission is done.

It should definitely give feedback.
Did you submit successfully? (Does your domain show up at https://hstspreload.appspot.com/pending ?)

**Comment by Joostvanderlaan** [comment]
@lgarron  Yeah, it does show up. It didn't give feedback.

**Comment by lgarron** [comment]
> @lgarron Yeah, it does show up. It didn't give feedback.

That is strange. Could you let me know exactly what you put in the domain input at the top of the page?

**Comment by Joostvanderlaan** [comment]
fashionunited.nz
nothing more, nothing less :)

**Comment by lgarron** [comment]
Here's what happens when I submit `fashionunited.nz` to (a test server of) the version of the submission site running at the time of submission for `fashionunited.nz`:

<img width="741" alt="screen shot 2016-06-13 at 13 58 48" src="https://cloud.githubusercontent.com/assets/248078/16022893/fefc5ab8-316e-11e6-98ab-b107aa538110.png">

(The same happens for the current version of the site.)

Are you *sure* you didn't get the "fashionunited.nz is now pending inclusion in the HSTS preload list!" message? I'm usually willing to consider I made a mistake, but I have never seen that message fail to show up while testing.

Is there a chance you didn't catch it because it wasn't highlighted enough, or because the rest of the page didn't change? We could certainly work on that.

**Comment by Joostvanderlaan** [comment]
Tested with another domain of ours, fashionunited.mx. I did get the message. Guess I just missed it then last time, cause it looks very similar to the rest of the page. Maybe you could add some CSS to clarify things. It's clear for me now, but I can understand others will get confused too. Thanks for your help.

**Comment by lgarron** [comment]
> Maybe you could add some CSS to clarify things.

I've separated the message into a third section and given it a header. Hopefully that will be sufficient.

![Uploading Screen Shot 2016-06-21 at 12.41.10.png…]()

**Comment by Joostvanderlaan** [comment]
I've submitted some more domains, I can confirm things are more clear now. Thanks!
