### ISSUE TITLE
Add an explicit advice section.

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload.appspot.com#62]
If we don't give advice, people are going to make up their own stuff, or get it from somewhere else. The following is a strawman based on existing best practices that I've seen:

## High-traffic, established site:

- Start with `max-age=3600; includeSubDomains` (1 hour).
- Ramp up the max-age: `86400` (1 day), `604800` (1 week), `2592000` (1 month).
- Run each ramp-up stage for at least as long as the length of the `max-age` for that stage (e.g. spend at least one month sending `2592000` ).
- If you have a group of dogfood users/beta testers (e.g. people inside your organization who), try the first few stages on just that subset of users. Then make sure to go through all stages for all users, starting over from `3600` (1 hour).
- If the last stage is working without problems, increase to `31536000` (1 year) and preload once you're comfortable.

## New site or site where consequences of breakage are not extreme:

Try the `604800` (1 week) step until you're comfortable there is no significant breakage, then go ahead and increase to `31536000` (1 year) and preload.

## TODO/Ideas

- Recommend looking at CSP (reporting HTTP resources?) and `upgrade-insecure-requests`?

--------

I think it's worth recommending 1 year because this is good protection without being gratuitously long. Easy to remember, easy to tell someone, and feels natural. It is also on the order of magnitude as a domain registration cycle.
(And if you visit a site less than once per year, the benefit from trying to protect recurrent visits is more questionable. But maybe this should be 2 years for yearly events that can shift seasons?)

In practice, it seems there is little benefit from sending 18 weeks instead of 1 year, since

1. to undo a dynamic HSTS rollout, you'll have to switch to `max-age=0` either way, and
2. if you preload and change your mind, the max-age doesn't affect your ability to recover very quickly. 

That is, if you shoot yourself in the foot, 18 weeks is not shooting yourself significantly less in the foot than 1 year.

@marumari @agl @estark37 @ScottHelme Thoughts?

**Comment by marumari** [comment]
I think that having a **Deployment Strategy** section is a great idea.  One thing to consider is instead of adding it to the hstspreload site, we instead update the Mozilla Web Security guidelines to include this information and point people there.

For busy sites, I usually start with `300` -> `3600` -> `259200` (being three days, but a week is also fine) and then move right up to a year.  `3600` is usually too long if it breaks something, hence the initial `300` recommendation.

Plain HSTS (sans preload and sans includeSubDomain) is pretty resilient against people making horrible mistakes, and I've rarely seen them in practice, since you have to have HTTPS working in the first place to get HSTS.

Reporting is a complete nightmare; most sites will generally find out pretty quickly if something has gone awry through other means, such as monitoring their traffic load or getting bucketloads of customer complaints.

I do really like `upgrade-insecure-requests` and I hope to work it into the web security guidelines as a general recommendation soon, if I can figure out a good way to do so cleanly.

As a general aside, I've thought a lot about the recommended max-age.  The initial Mozilla recommendations were a year for the reasons you listed, and because it was the most common value seen in the wild.  But I do think that something like 13-14 months is probably a better number _in general_ because there are many things that I do on an annual basis, but often I will do them a little over a year apart.

Good example of this kind of activity would include filing my taxes; maybe done on February 20th one year, and March 15th the next year. I think most people would agree that keeping HSTS in this context is the proper thing to do.

**Comment by lgarron** [comment]
> One thing to consider is instead of adding it to the hstspreload site, we instead update the Mozilla Web Security guidelines to include this information and point people there.

I strongly think we should put something on the page itself, but I'd love to link to Mozilla guidelines. Especially if those guidelines had [concrete code snippets for Apache/nginx](https://github.com/chromium/hstspreload.appspot.com/issues/42) that satisfy the preload requirements.

> For busy sites, I usually start with 300 -> 3600 -> 259200 (being three days, but a week is also fine) and then move right up to a year. 3600 is usually too long if it breaks something, hence the initial 300 recommendation.

Hmm, the more I think about it, the more I want to combine the two cases and reduce steps (I expect sites to adjust the advice based on how conservative they are, anyhow).

`300` sounds reasonable, but I also really want to include something like a month. I get the feeling people run into problems if they implement it in a one-week sprint and then put it out of their mind. One month is also the longest natural length to catch recurring problems below 18 weeks/1 year (e.g. a site for monthly rent/lease payments).

> Good example of this kind of activity would include filing my taxes; maybe done on February 20th one year, and March 15th the next year. I think most people would agree that keeping HSTS in this context is the proper thing to do.

Matches my thoughts exactly. How common is 2 years? Could you post the distribution here?

> Reporting is a complete nightmare; most sites will generally find out pretty quickly if something has gone awry through other means, such as monitoring their traffic load or getting bucketloads of customer complaints.

Sounds fair. We can always add it later.

> Plain HSTS (sans preload and sans includeSubDomain)

Since this is `hstspreload` advice and preloading includes subdomains, I'd rather have "include subdomains" be the default right answer and have sites test with it from the start.
Keeps it simple, and probably matches what people want if their goal is to preload (which is hopefully why they're on `hstspreload.appspot.com`).

How's this?

- Start with `max-age=300; includeSubdomains` (5 minutes).
- Ramp up the max-age: `604800` (1 week), `2592000` (1 month).
- Run each ramp-up stage for at least as long as the length of the max-age for that stage (e.g. spend at least one month sending `2592000` ).
- If the last stage is working without problems, increase to `31536000` (1 year) and preload once you're comfortable.

Extra advice:
- If you have a group of dogfood users/beta testers, try the first few stages on just that subset of users. Then make sure to go through all stages for all users, starting over from 300 (5 minutes).
- Look at the Mozilla guidelines for more concrete details and related mechanisms. In particular, consider trying `upgrade-insecure-requests`.

**Comment by marumari** [comment]
I'll respond to the rest as soon as I can, but I need to get some 💤.

> Matches my thoughts exactly. How common is 2 years? Could you post the distribution here?

https://gist.github.com/marumari/eb756a7899becce19f619910f019039e (Alexa 1M, as of last April)
https://gist.github.com/marumari/0d88fce62fa8a860d14b4a33dcf74a17 (As above, but only sites that had set preload, although not necessarily were preloaded)

**Comment by lgarron** [comment]
Counts above 50 from your list (where preload was set):

    63072000     |   893
    31536000     |   862
    15552000     |   505
    0            |   209
    15768000     |   119
    10886400     |    86
    2592000      |    83

Counts above 50 from a scan of preloaded sites I did in May:

    {
     {31556926, 68},
     {315360000, 71},
     {16070400, 91},
     {10886400, 313},
     {15768000, 762},
     {15552000, 1295},
     {31536000, 3189},
     {63072000, 3821}
    }

There were 12600 entries, and the counts above include all `10191` sites that send a header (regardless of whether they send the `preload` directive).

Sounds like `63072000` (2 years) is more popular than 1 year, or at least a very defensible choice. I'd say we should go with that.

**Comment by marumari** [comment]
I'm completely in accordance with making the recommendation two years, unless anybody has any objections.

Of course, there's not really much difference between `max-age=63072000` and `max-age=heat-death-of-the-universe`, but I just checked the specification and it seems that nobody made that a keyword.  😭

**Comment by ScottHelme** [comment]
I agree with the max-age being 2 years. Once we get up above a month or two then I don't think it really matters. Also, it may be beneficial to have such a large number to give people a reason to pause and think about it a bit more. 

I also prefer the single timeline for deployment rather than trying to split it. All sites should ease in and monitor as they go regardless of size.

👍

**Comment by estark37** [comment]
Didn't read the whole thread yet (still on vacation) but ISTR that chrome
(and maybe FF too?) enforces max max-age of 1 year, so not sure if a
recommendation of 2 years makes sense.

**Comment by marumari** [comment]
Firefox enforces a max max-age (delightfully named `mMaxMaxAge`) for HPKP (60 days), but has no upper limit for HSTS.

**Comment by lgarron** [comment]
> ISTR that chrome
> (and maybe FF too?) enforces max max-age of 1 year

Hmm, that sounds vaguely familiar. I guess I should find out where and why.
